export { default as HeroImage } from '../assets/images/hero.png'
export { default as Avatar } from '../assets/images/avatar.png'
export { default as Hotels } from '../assets/images/hotel.png'
export { default as Attractions } from '../assets/images/attraction.png'
export { default as Reastaurants } from '../assets/images/restaurants.png'
